const MB='https://musicbrainz.org/ws/2';
const headers={Accept:'application/json','User-Agent':'Ritim/0.4 personal-android-client'};
async function mb(path:string){const r=await fetch(`${MB}/${path}`,{headers});if(!r.ok)throw new Error(`MusicBrainz ${r.status}`);return r.json()}
export type ArtistProfile={id:string;name:string;country?:string;type?:string;disambiguation?:string;tags:string[]};
export type ReleaseGroup={id:string;title:string;type?:string;firstReleaseDate?:string;artworkUrl?:string};
export async function findArtist(name:string):Promise<ArtistProfile|null>{const j=await mb(`artist?query=${encodeURIComponent(`artist:${name}`)}&fmt=json&limit=5`);const a=j.artists?.[0];return a?{id:a.id,name:a.name,country:a.country,type:a.type,disambiguation:a.disambiguation,tags:(a.tags||[]).sort((x:any,y:any)=>(y.count||0)-(x.count||0)).slice(0,12).map((x:any)=>x.name)}:null}
export async function artistReleases(artistId:string):Promise<ReleaseGroup[]>{const j=await mb(`release-group?artist=${encodeURIComponent(artistId)}&fmt=json&limit=100&type=album|ep|single`);const rows=(j['release-groups']||[]).map((x:any)=>({id:x.id,title:x.title,type:x['primary-type'],firstReleaseDate:x['first-release-date']}));return Promise.all(rows.map(async(x:any)=>({...x,artworkUrl:await coverArt(x.id)})))}
export async function releaseTracks(releaseGroupId:string){const j=await mb(`release?release-group=${encodeURIComponent(releaseGroupId)}&fmt=json&limit=10&inc=recordings`);const release=j.releases?.[0];if(!release)return[];const full=await mb(`release/${release.id}?fmt=json&inc=recordings+artist-credits`);return(full.media||[]).flatMap((m:any)=>m.tracks||[]).map((t:any)=>({id:`mb:${t.recording?.id||t.id}`,source:'musicbrainz' as const,title:t.title,artist:t['artist-credit']?.map((a:any)=>a.name).join('')||release['artist-credit']?.map((a:any)=>a.name).join('')||'Bilinmeyen sanatçı',album:release.title,duration:t.length?Math.round(t.length/1000):undefined}))}
export async function coverArt(releaseGroupId:string):Promise<string|undefined>{try{const r=await fetch(`https://coverartarchive.org/release-group/${encodeURIComponent(releaseGroupId)}`,{headers:{Accept:'application/json'}});if(!r.ok)return;const j=await r.json();const image=(j.images||[]).find((x:any)=>x.front)||(j.images||[])[0];return image?.thumbnails?.['500']||image?.thumbnails?.large||image?.image}catch{return undefined}}
