import {File} from 'expo-file-system';
import * as LegacyFS from 'expo-file-system/legacy';
import * as Network from 'expo-network';
import type {Track} from '@/types/music';
import {trackFingerprint} from '@/lib/dedupe';
import * as SQLite from 'expo-sqlite';
import {loadPreferences} from './preferences';
import {resolveSmartCachedUri,smartCacheTrack} from './smartCache';

export type DownloadJobState='queued'|'downloading'|'paused'|'completed'|'failed'|'cancelled';
export type DownloadJob={id:string;track:Track;state:DownloadJobState;progress:number;bytesWritten:number;bytesExpected:number;error?:string};
const jobs=new Map<string,DownloadJob>();const resumables=new Map<string,any>();const listeners=new Set<(jobs:DownloadJob[])=>void>();let running=false;
const dir=`${LegacyFS.documentDirectory}ritim-downloads/`;
const snapshot=()=>[...jobs.values()];const emit=()=>listeners.forEach(fn=>fn(snapshot()));
export const subscribeDownloads=(fn:(items:DownloadJob[])=>void)=>{listeners.add(fn);fn(snapshot());return()=>listeners.delete(fn)};
async function ensureDir(){const info=await LegacyFS.getInfoAsync(dir);if(!info.exists)await LegacyFS.makeDirectoryAsync(dir,{intermediates:true})}
async function checkPolicy(){const prefs=await loadPreferences();if(!prefs.wifiOnlyDownloads)return;const n=await Network.getNetworkStateAsync();if(String(n.type).toUpperCase()!=='WIFI')throw new Error('İndirme yalnızca Wi‑Fi üzerinde açık.');}
async function persist(track:Track,uri:string,size:number){const db=await SQLite.openDatabaseAsync('ritim.db'),fp=trackFingerprint(track);await db.runAsync(`INSERT INTO downloads(fingerprint,track_json,local_uri,bytes,created_at) VALUES(?,?,?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET track_json=excluded.track_json,local_uri=excluded.local_uri,bytes=excluded.bytes,created_at=excluded.created_at`,fp,JSON.stringify(track),uri,size,Date.now())}
async function pump(){if(running)return;running=true;try{while(true){const job=snapshot().find(x=>x.state==='queued');if(!job)break;await runJob(job)}}finally{running=false}}
async function runJob(job:DownloadJob){if(!job.track.streamUrl)return;job.state='downloading';emit();try{await checkPolicy();await ensureDir();const safe=job.id.replace(/[^a-z0-9_-]/gi,'_').slice(0,100),target=`${dir}${safe}.audio`;const resumable=LegacyFS.createDownloadResumable(job.track.streamUrl,target,{},p=>{job.bytesWritten=p.totalBytesWritten;job.bytesExpected=p.totalBytesExpectedToWrite||0;job.progress=job.bytesExpected?job.bytesWritten/job.bytesExpected:0;emit()});resumables.set(job.id,resumable);const result=await resumable.downloadAsync();if(job.state==='cancelled'||job.state==='paused')return;if(!result?.uri)throw new Error('Dosya indirilemedi.');const info=await LegacyFS.getInfoAsync(result.uri,{size:true});await persist(job.track,result.uri,(info as any).size||job.bytesWritten||0);job.progress=1;job.state='completed';emit()}catch(e){if(job.state!=='paused'&&job.state!=='cancelled'){job.state='failed';job.error=e instanceof Error?e.message:'İndirme başarısız';emit()}}finally{resumables.delete(job.id)}}
export async function downloadTrack(track:Track){if(!track.streamUrl)throw new Error('Bu parça indirilemiyor.');const id=trackFingerprint(track);const old=jobs.get(id);if(old?.state==='completed'){const local=await resolvePlayableUri(track);if(local)return local}const job:DownloadJob={id,track,state:'queued',progress:0,bytesWritten:0,bytesExpected:0};jobs.set(id,job);emit();pump();return new Promise<string>((resolve,reject)=>{const off=subscribeDownloads(items=>{const x=items.find(j=>j.id===id);if(x?.state==='completed'){off();resolve(resolvePlayableUri(track) as any)}else if(x?.state==='failed'||x?.state==='cancelled'){off();reject(new Error(x.error||'İndirme iptal edildi.'))}}) as unknown as Promise<string>}
export async function pauseDownload(id:string){const job=jobs.get(id),r=resumables.get(id);if(!job||!r||job.state!=='downloading')return;await r.pauseAsync();job.state='paused';emit()}
export async function resumeDownload(id:string){const job=jobs.get(id),r=resumables.get(id);if(!job||!r||job.state!=='paused')return;job.state='downloading';emit();try{const result=await r.resumeAsync();if(result?.uri){const info=await LegacyFS.getInfoAsync(result.uri,{size:true});await persist(job.track,result.uri,(info as any).size||job.bytesWritten);job.progress=1;job.state='completed';emit()}}catch(e){job.state='failed';job.error=e instanceof Error?e.message:'Devam ettirilemedi';emit()}}
export async function cancelDownload(id:string){const job=jobs.get(id),r=resumables.get(id);if(r)try{await r.cancelAsync()}catch{}if(job){job.state='cancelled';emit()}}
export async function removeDownload(track:Track){const fingerprint=trackFingerprint(track);const db=await SQLite.openDatabaseAsync('ritim.db');const row=await db.getFirstAsync<{local_uri:string}>('SELECT local_uri FROM downloads WHERE fingerprint=?',fingerprint);if(row?.local_uri)try{await LegacyFS.deleteAsync(row.local_uri,{idempotent:true})}catch{}await db.runAsync('DELETE FROM downloads WHERE fingerprint=?',fingerprint);jobs.delete(fingerprint);emit()}
export async function resolvePlayableUri(track:Track):Promise<string|undefined>{if(track.source==='local')return track.streamUrl;const fingerprint=trackFingerprint(track);const db=await SQLite.openDatabaseAsync('ritim.db');const row=await db.getFirstAsync<{local_uri:string}>('SELECT local_uri FROM downloads WHERE fingerprint=?',fingerprint);if(row?.local_uri){try{if(new File(row.local_uri).exists)return row.local_uri}catch{}}const cached=await resolveSmartCachedUri(track);if(cached)return cached;loadPreferences().then(p=>{if(p.autoCache&&track.streamUrl)smartCacheTrack(track).catch(()=>{})}).catch(()=>{});return track.streamUrl;}
export async function listDownloads(){const db=await SQLite.openDatabaseAsync('ritim.db');const rows=await db.getAllAsync<{track_json:string;local_uri:string;bytes:number;created_at:number}>('SELECT track_json,local_uri,bytes,created_at FROM downloads ORDER BY created_at DESC');return rows.map(r=>({track:JSON.parse(r.track_json) as Track,localUri:r.local_uri,bytes:r.bytes,createdAt:r.created_at}))}
export async function totalDownloadedBytes(){return(await listDownloads()).reduce((a,b)=>a+(b.bytes||0),0)}
