import {Directory,File,Paths} from 'expo-file-system';
import * as SQLite from 'expo-sqlite';
import type {Track} from '@/types/music';
import {trackFingerprint} from '@/lib/dedupe';
import {loadPreferences} from '@/services/preferences';
import {topStats} from '@/storage/database';

const dir=new Directory(Paths.cache,'ritim-smart-cache');
async function store(){if(!dir.exists)dir.create();const db=await SQLite.openDatabaseAsync('ritim.db');await db.execAsync(`CREATE TABLE IF NOT EXISTS stream_cache(fingerprint TEXT PRIMARY KEY,track_json TEXT NOT NULL,local_uri TEXT NOT NULL,bytes INTEGER NOT NULL DEFAULT 0,last_access INTEGER NOT NULL);`);return db}
export async function resolveSmartCachedUri(track:Track){const db=await store(),fp=trackFingerprint(track);const row=await db.getFirstAsync<{local_uri:string}>('SELECT local_uri FROM stream_cache WHERE fingerprint=?',fp);if(!row)return;try{const f=new File(row.local_uri);if(!f.exists){await db.runAsync('DELETE FROM stream_cache WHERE fingerprint=?',fp);return}await db.runAsync('UPDATE stream_cache SET last_access=? WHERE fingerprint=?',Date.now(),fp);return row.local_uri}catch{return}}
export async function smartCacheTrack(track:Track){if(!track.streamUrl||track.source==='radio'||track.source==='local')return;const db=await store(),fp=trackFingerprint(track);if(await resolveSmartCachedUri(track))return;const safe=fp.replace(/[^a-z0-9_-]/gi,'_').slice(0,100),target=new File(dir,`${safe}.audio`);try{const downloaded=await File.downloadFileAsync(track.streamUrl,target,{idempotent:true});await db.runAsync(`INSERT INTO stream_cache(fingerprint,track_json,local_uri,bytes,last_access) VALUES(?,?,?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET track_json=excluded.track_json,local_uri=excluded.local_uri,bytes=excluded.bytes,last_access=excluded.last_access`,fp,JSON.stringify(track),downloaded.uri,downloaded.size??0,Date.now());await enforceCacheLimit()}catch{}}
export async function enforceCacheLimit(){const prefs=await loadPreferences(),db=await store(),limit=Math.max(64,prefs.cacheLimitMb)*1024*1024;const rows=await db.getAllAsync<{fingerprint:string;local_uri:string;bytes:number}>('SELECT fingerprint,local_uri,bytes FROM stream_cache ORDER BY last_access ASC');let total=rows.reduce((n,x)=>n+(x.bytes||0),0);for(const row of rows){if(total<=limit)break;try{const f=new File(row.local_uri);if(f.exists)f.delete()}catch{}await db.runAsync('DELETE FROM stream_cache WHERE fingerprint=?',row.fingerprint);total-=row.bytes||0}return total}
export async function warmSmartCache(maxTracks=12){const prefs=await loadPreferences();if(!prefs.autoCache)return;const rows=await topStats(maxTracks*3),tracks=rows.map(r=>JSON.parse(r.track_json) as Track).filter(t=>!!t.streamUrl&&t.source!=='radio'&&t.source!=='local').slice(0,maxTracks);for(const t of tracks)await smartCacheTrack(t);}
export async function clearSmartCache(){const db=await store();const rows=await db.getAllAsync<{local_uri:string}>('SELECT local_uri FROM stream_cache');for(const r of rows){try{const f=new File(r.local_uri);if(f.exists)f.delete()}catch{}}await db.runAsync('DELETE FROM stream_cache')}
export async function smartCacheBytes(){const db=await store();const r=await db.getFirstAsync<{total:number}>('SELECT COALESCE(SUM(bytes),0) total FROM stream_cache');return r?.total||0}
