import{ImageBackground,PanResponder,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{useMemo,useState}from'react';
import{Image}from'expo-image';
import{useRouter}from'expo-router';
import{useSafeAreaInsets}from'react-native-safe-area-context';
import*as Haptics from'expo-haptics';
import{colors}from'@/theme';import{usePlayer}from'@/context/PlayerContext';import{useRitimLayout}from'@/ui/layout';
const tm=(v:number)=>`${Math.floor((v||0)/60)}:${String(Math.floor(v||0)%60).padStart(2,'0')}`;
export default function Player(){
 const r=useRouter(),insets=useSafeAreaInsets(),l=useRitimLayout();const[trackWidth,setTrackWidth]=useState(1);
 const{currentTrack,isPlaying,currentTime,duration,toggle,next,previous,seekTo,shuffle,repeat,setShuffle,cycleRepeat,playbackRate,sleepEndsAt}=usePlayer();
 const pan=useMemo(()=>PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)>18||Math.abs(g.dy)>18,onPanResponderRelease:(_,g)=>{if(Math.abs(g.dy)>Math.abs(g.dx)&&g.dy>90){Haptics.selectionAsync();r.back();return}if(Math.abs(g.dx)>80){Haptics.selectionAsync();g.dx<0?next():previous()}}}),[currentTrack?.id,next,previous]);
 if(!currentTrack)return <View style={s.empty}><Text style={s.title}>Henüz bir şey çalmıyor.</Text><Pressable onPress={()=>r.back()}><Text style={s.link}>Geri dön</Text></Pressable></View>;
 const p=duration?Math.min(100,currentTime/duration*100):0,live=currentTrack.source==='radio'||currentTrack.artist==='Canlı Radyo';
 return <View style={s.root}>{currentTrack.artworkUrl&&<ImageBackground source={{uri:currentTrack.artworkUrl}} blurRadius={55} style={StyleSheet.absoluteFill}><View style={s.scrim}/></ImageBackground>}
 <ScrollView style={s.c} contentContainerStyle={{paddingTop:Math.max(insets.top+12,44),paddingBottom:Math.max(insets.bottom+40,60)}}>
  <View style={[s.shell,{maxWidth:l.tablet?620:l.maxContentWidth,paddingHorizontal:l.horizontalPadding}]}> 
   <View style={s.top}><Pressable onPress={()=>r.back()}><Text style={s.back}>⌄</Text></Pressable><Text style={s.now}>ŞU ANDA ÇALIYOR</Text><Pressable onPress={()=>r.push('/settings')}><Text style={s.more}>•••</Text></Pressable></View>
   <View {...pan.panHandlers} style={s.coverWrap}>{currentTrack.artworkUrl?<Image source={{uri:currentTrack.artworkUrl}} style={[s.cover,{width:l.playerArtworkSize,height:l.playerArtworkSize}]}/>:<View style={[s.cover,{width:l.playerArtworkSize,height:l.playerArtworkSize}]}><Text style={s.note}>♪</Text></View>}</View>
   <Text style={[s.title,l.compact&&{fontSize:24}]} numberOfLines={2}>{currentTrack.title}</Text>
   <Pressable onPress={()=>!live&&r.push({pathname:'/artist/[name]',params:{name:currentTrack.artist}})}><Text style={s.artist}>{currentTrack.artist}</Text></Pressable>
   <Pressable disabled={live||!duration} onLayout={e=>setTrackWidth(Math.max(1,e.nativeEvent.layout.width))} onPress={e=>seekTo(Math.max(0,Math.min(duration,(e.nativeEvent.locationX/trackWidth)*duration)))} style={s.track}><View style={[s.fill,{width:`${p}%`}]}/></Pressable>
   <View style={s.times}><Text style={s.time}>{tm(currentTime)}</Text><Text style={s.time}>{duration?tm(duration):'CANLI'}</Text></View>
   <View style={s.modeRow}><Pressable onPress={()=>setShuffle(!shuffle)}><Text style={[s.mode,shuffle&&s.on]}>⇄</Text></Pressable><Pressable onPress={previous}><Text style={s.skip}>|◀</Text></Pressable><Pressable onPress={toggle} style={[s.main,l.compact&&{width:64,height:64,borderRadius:32}]}><Text style={s.mainText}>{isPlaying?'Ⅱ':'▶'}</Text></Pressable><Pressable onPress={next}><Text style={s.skip}>▶|</Text></Pressable><Pressable onPress={cycleRepeat}><Text style={[s.mode,repeat!=='off'&&s.on]}>{repeat==='one'?'↻1':'↻'}</Text></Pressable></View>
   <View style={s.actions}>{!live&&<Pressable onPress={()=>r.push('/lyrics')} style={s.action}><Text style={s.at}>Sözler</Text></Pressable>}<Pressable onPress={()=>r.push('/queue')} style={s.action}><Text style={s.at}>Sıra</Text></Pressable><Pressable onPress={()=>r.push('/settings')} style={s.action}><Text style={s.at}>{playbackRate.toFixed(2)}x</Text></Pressable></View>
   {sleepEndsAt?<Text style={s.sleep}>Uyku zamanlayıcısı: {Math.max(1,Math.ceil((sleepEndsAt-Date.now())/60000))} dk</Text>:null}<Text style={s.hint}>← / → kaydır: parça değiştir • ↓ kaydır: küçült</Text>
  </View>
 </ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},scrim:{flex:1,backgroundColor:'rgba(9,11,10,.78)'},c:{flex:1},shell:{width:'100%',alignSelf:'center'},empty:{flex:1,backgroundColor:colors.bg,alignItems:'center',justifyContent:'center'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{color:colors.text,fontSize:30},now:{color:colors.muted,fontWeight:'800',fontSize:11,letterSpacing:1.4},more:{color:colors.text,fontSize:18,fontWeight:'900'},coverWrap:{alignItems:'center'},cover:{borderRadius:28,backgroundColor:colors.card2,marginTop:24,alignItems:'center',justifyContent:'center'},note:{color:colors.green,fontSize:90},title:{color:colors.text,fontSize:27,fontWeight:'900',marginTop:24},artist:{color:colors.green,fontSize:15,fontWeight:'800',marginTop:6},track:{height:7,borderRadius:99,backgroundColor:'rgba(255,255,255,.14)',marginTop:28,overflow:'hidden'},fill:{height:'100%',backgroundColor:colors.green},times:{flexDirection:'row',justifyContent:'space-between',marginTop:8},time:{color:colors.muted,fontSize:11},modeRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:22},main:{width:72,height:72,borderRadius:36,backgroundColor:colors.green,alignItems:'center',justifyContent:'center'},mainText:{color:colors.bg,fontSize:28,fontWeight:'900'},skip:{color:colors.text,fontSize:20,fontWeight:'800'},mode:{color:colors.muted,fontSize:22,fontWeight:'900'},on:{color:colors.green},actions:{flexDirection:'row',gap:9,marginTop:24},action:{flex:1,minHeight:46,borderRadius:14,backgroundColor:'rgba(19,23,20,.82)',borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},at:{color:colors.text,fontWeight:'800'},sleep:{color:colors.muted,textAlign:'center',marginTop:16},hint:{color:'#69726B',textAlign:'center',fontSize:11,marginTop:20},link:{color:colors.green,marginTop:12}});
