import{useEffect,useRef,useState}from'react';
import{ActivityIndicator,FlatList,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{useSafeAreaInsets}from'react-native-safe-area-context';
import{colors}from'@/theme';import{searchAllMusic}from'@/services/search';import{recentSearches}from'@/storage/database';import type{Track}from'@/types/music';import{TrackRow}from'@/components/TrackRow';import{useRitimLayout}from'@/ui/layout';
export default function Search(){
 const insets=useSafeAreaInsets(),l=useRitimLayout();const[q,setQ]=useState('');const[tracks,setTracks]=useState<Track[]>([]);const[recent,setRecent]=useState<string[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const seq=useRef(0);
 useEffect(()=>{recentSearches().then(x=>setRecent(x.map(r=>r.query)))},[]);useEffect(()=>{const query=q.trim();if(query.length<2){setTracks([]);setLoading(false);return}const id=setTimeout(()=>run(query),600);return()=>clearTimeout(id)},[q]);
 const run=async(query=q.trim())=>{if(query.length<2)return;const n=++seq.current;setLoading(true);setError('');try{const result=await searchAllMusic(query);if(n===seq.current){setTracks(result);recentSearches().then(x=>setRecent(x.map(r=>r.query)))}}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Arama başarısız')}finally{if(n===seq.current)setLoading(false)}};
 return <View style={s.c}><View style={[s.shell,{maxWidth:l.maxContentWidth,paddingHorizontal:l.horizontalPadding,paddingTop:Math.max(insets.top+18,52)}]}><Text style={[s.h,l.compact&&{fontSize:29}]}>Ara</Text><View style={s.bar}><TextInput value={q} onChangeText={setQ} onSubmitEditing={()=>run()} placeholder="Şarkı, sanatçı veya albüm" placeholderTextColor={colors.muted} autoCorrect={false} returnKeyType="search" style={s.i}/>{q.length>0&&<Pressable onPress={()=>{setQ('');setTracks([])}} style={s.clear}><Text style={s.clearText}>×</Text></Pressable>}</View>{!q&&recent.length>0&&<><Text style={s.label}>Son aramalar</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{recent.map(x=><Pressable key={x} onPress={()=>setQ(x)} style={s.chip}><Text style={s.chipText}>{x}</Text></Pressable>)}</ScrollView></>}{loading&&<View style={s.loading}><ActivityIndicator color={colors.green}/><Text style={s.loadingText}>Kaynaklar taranıyor…</Text></View>}{error?<Text style={s.err}>{error}</Text>:<FlatList data={tracks} keyExtractor={(x,i)=>`${x.id}-${i}`} contentContainerStyle={{paddingBottom:160}} showsVerticalScrollIndicator={false} renderItem={({item})=><TrackRow track={item} queue={tracks.filter(x=>!!x.streamUrl)}/>} ListEmptyComponent={!loading&&q.length>=2?<Text style={s.empty}>Sonuç bulunamadı.</Text>:null}/>}</View></View>
}
const s=StyleSheet.create({c:{flex:1,backgroundColor:colors.bg},shell:{flex:1,width:'100%',alignSelf:'center'},h:{color:colors.text,fontSize:34,fontWeight:'900'},bar:{position:'relative',marginTop:18,marginBottom:10},i:{height:52,borderRadius:16,backgroundColor:colors.card,color:colors.text,paddingHorizontal:15,paddingRight:45,borderWidth:1,borderColor:colors.line,fontSize:15},clear:{position:'absolute',right:5,top:5,width:42,height:42,alignItems:'center',justifyContent:'center'},clearText:{color:colors.muted,fontSize:28},label:{color:colors.muted,fontSize:12,fontWeight:'800',marginTop:6},chips:{gap:7,paddingVertical:10},chip:{paddingHorizontal:12,paddingVertical:9,borderRadius:999,backgroundColor:colors.card,borderWidth:1,borderColor:colors.line},chipText:{color:colors.text,fontWeight:'700',fontSize:12},loading:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:14},loadingText:{color:colors.muted},err:{color:colors.danger,marginTop:20},empty:{color:colors.muted,textAlign:'center',marginTop:50}});
