import {healthScore} from './sourceHealth.js';
const clean=(v='')=>String(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9ığüşöç\s]/gi,' ').replace(/\s+/g,' ').trim();
export const fingerprint=t=>t.isrc?`isrc:${String(t.isrc).toUpperCase()}`:`${clean(t.artist)}|${clean(t.title)}`;
export const sourceScore=t=>Number(!!t.streamUrl)*50+Number(!!t.artworkUrl)*8+Number(!!t.duration)*5+Number(!!t.isrc)*18+(t.source==='openverse'?8:t.source==='internetarchive'?6:0)+(t.streamUrl?healthScore(t.streamUrl):0);
export function bestWithAlternatives(items){const m=new Map();for(const x of items){const k=fingerprint(x),l=m.get(k)||[];l.push({...x,sourceScore:sourceScore(x)});m.set(k,l)}return[...m.values()].map(l=>{l.sort((a,b)=>b.sourceScore-a.sourceScore);return{...l[0],alternatives:l.slice(1).filter(x=>x.streamUrl).map(x=>({source:x.source,streamUrl:x.streamUrl,sourceScore:x.sourceScore,license:x.license}))}}).sort((a,b)=>b.sourceScore-a.sourceScore)}
async function timed(url,options={},ms=9000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...options,signal:c.signal})}finally{clearTimeout(timer)}}
export async function musicBrainz(q){const r=await timed(`https://musicbrainz.org/ws/2/recording?query=${encodeURIComponent(q)}&fmt=json&limit=25`,{headers:{'User-Agent':'Ritim/0.5 personal-android-client',Accept:'application/json'}});if(!r.ok)throw new Error(`MusicBrainz ${r.status}`);const j=await r.json();return(j.recordings||[]).map(x=>({id:`mb:${x.id}`,source:'musicbrainz',title:x.title,artist:x['artist-credit']?.map(a=>a.name).join('')||'Bilinmeyen sanatçı',album:x.releases?.[0]?.title,duration:x.length?Math.round(x.length/1000):undefined,isrc:x.isrcs?.[0]}))}
export async function openverse(q){const r=await timed(`https://api.openverse.org/v1/audio/?q=${encodeURIComponent(q)}&page_size=25`);if(!r.ok)throw new Error(`Openverse ${r.status}`);const j=await r.json();return(j.results||[]).map(x=>({id:`ov:${x.id}`,source:'openverse',title:x.title||'İsimsiz parça',artist:x.creator||'Bilinmeyen sanatçı',artworkUrl:x.thumbnail||undefined,streamUrl:x.url||x.audio_url||undefined,duration:typeof x.duration==='number'?Math.round(x.duration):undefined,license:x.license?`${x.license}${x.license_version?` ${x.license_version}`:''}`:undefined}))}
export async function archive(q){const p=new URLSearchParams({q:`mediatype:audio AND (${q})`,fl:'identifier,title,creator',rows:'10',output:'json'});const r=await timed(`https://archive.org/advancedsearch.php?${p}`);if(!r.ok)throw new Error(`Archive ${r.status}`);const j=await r.json();const settled=await Promise.allSettled((j.response?.docs||[]).map(async d=>{const mr=await timed(`https://archive.org/metadata/${encodeURIComponent(d.identifier)}`);if(!mr.ok)return null;const m=await mr.json();const audio=(m.files||[]).find(f=>typeof f.name==='string'&&/\.(mp3|m4a|ogg|flac)$/i.test(f.name)&&!/64kb|spectrogram|thumb/i.test(f.name));if(!audio)return null;return{id:`ia:${d.identifier}:${audio.name}`,source:'internetarchive',title:m.metadata?.title||d.title||audio.title||d.identifier,artist:m.metadata?.creator||d.creator||'Bilinmeyen sanatçı',album:m.metadata?.album||undefined,artworkUrl:`https://archive.org/download/${encodeURIComponent(d.identifier)}/__ia_thumb.jpg`,streamUrl:`https://archive.org/download/${encodeURIComponent(d.identifier)}/${encodeURIComponent(audio.name)}`,duration:audio.length?Math.round(Number(audio.length)):undefined,license:m.metadata?.licenseurl||m.metadata?.rights||undefined,format:audio.format||undefined,size:audio.size?Number(audio.size):undefined}}));return settled.flatMap(x=>x.status==='fulfilled'&&x.value?[x.value]:[])}
export async function searchSources(q){const settled=await Promise.allSettled([openverse(q),archive(q),musicBrainz(q)]),all=[],errors=[];for(const x of settled){if(x.status==='fulfilled')all.push(...x.value);else errors.push(String(x.reason?.message||x.reason))}return{tracks:bestWithAlternatives(all),errors}}
